training_mode: True
use_gpu: True
checkpoint_path: "app/energy_agent/models/ppo_model_last.pth"

actor_lr: 0.0001
critic_lr: 0.0003

energy_coeff: 0.1
drop_magnitude_penalty_coef: 100.0
latency_magnitude_penalty_coef: 100.0
cpu_magnitude_penalty_coef: 100.0
prb_magnitude_penalty_coef: 100.0
improvement_coeff: 5.0

violation_event_penalty: -5.0
energy_consumption_penalty: -1000.0

gamma: 0.99
lambda_gae: 0.95
clip_epsilon: 0.2
ppo_epochs: 8
batch_size: 32
buffer_size: 512
n_envs: 4
hidden_dim: 256
