training_mode: False
use_gpu: True
checkpoint_path: "app/energy_agent/models/ppo_model_6k.pth"

actor_lr: 0.0001
critic_lr: 0.0003

energy_coeff: 0.01
drop_magnitude_penalty_coef: 1.0
latency_magnitude_penalty_coef: 0.5
cpu_magnitude_penalty_coef: 1.0
prb_magnitude_penalty_coef: 1.0
improvement_coeff: 0.5

violation_event_penalty: -10.0
energy_consumption_penalty: -10.0

gamma: 0.99
lambda_gae: 0.95
clip_epsilon: 0.2
ppo_epochs: 8
batch_size: 64
buffer_size: 2048
n_envs: 4
hidden_dim: 256

